#!/usr/bin/env bash
set -euo pipefail

# Credit to sam for some of the container adjustments:
# https://wiki.gentoo.org/wiki/User:Sam/Quick_Docker
cat >> /etc/portage/make.conf <<-EOF
	FEATURES="\${FEATURES} -ipc-sandbox -pid-sandbox -network-sandbox -usersandbox -mount-sandbox -sandbox"
	FEATURES="\${FEATURES} -news -merge-sync"
	FEATURES="\${FEATURES} parallel-install parallel-fetch"
	# FEATURES="\${FEATURES} buildpkg"
	FEATURES="\${FEATURES} binpkg-request-signature"

	EMERGE_DEFAULT_OPTS="--jobs 3 --binpkg-respect-use=y --getbinpkg=y"

	LINGUAS="en de"
	L10N="en de"

	BINPKG_COMPRESS="xz"

	PORTAGE_RO_DISTDIRS="/ro-distdir"
EOF

NPROC=$(nproc)
export MAKEOPTS="--jobs ${NPROC} --load-average ${NPROC}"

mkdir /etc/portage/package.unmask

# Pull in kitty fix from latest gentoo-functions
cat > /etc/portage/package.accept_keywords/gentoo-functions <<EOF
<sys-apps/gentoo-functions-1.7
EOF
emerge -1 gentoo-functions

emerge-world() {
	emerge \
	--update \
	--changed-use \
	--deep \
	--complete-graph \
	--with-bdeps=y \
	--backtrack=100 \
	--tree \
	--unordered-display \
	--usepkg y \
	@world
}

emerge-world

emerge dev-vcs/git

rm -rf /var/db/repos/gentoo

mkdir /etc/portage/repos.conf
# Note: We do not enable sync-git-verify-commit-signature here.
cat > /etc/portage/repos.conf/gentoo.conf <<-EOF
	[gentoo]
	location = /var/db/repos/gentoo
	sync-type = git
	sync-uri = https://github.com/gentoo-mirror/gentoo.git
	sync-git-verify-commit-signature = yes
EOF

emerge --sync

emerge-world

BASE_PACKAGES=(
	app-eselect/eselect-repository
)

emerge "${BASE_PACKAGES[@]}"

OVERLAY_REPOS=(
	flow
	java
)

for REPO in "${OVERLAY_REPOS[@]}"; do
	eselect repository enable "${REPO}"
	emaint -r "${REPO}" sync
done

emerge --depclean

cat > /usr/local/bin/drop-distdir <<-EOF
	#!/usr/bin/env bash
	set -euo pipefail

	DISTDIR=$(portageq distdir)
	rm -rf "\${DISTDIR}"/*
EOF
chmod 755 /usr/local/bin/drop-distdir

cat > /usr/local/bin/drop-pkgdir <<-EOF
	#!/usr/bin/env bash
	set -euo pipefail

	PKGDIR=$(portageq pkgdir)
	rm -rf "\${PKGDIR}"/*
EOF
chmod 755 /usr/local/bin/drop-pkgdir

drop-distdir
drop-pkgdir

cat > /usr/local/bin/force-update-conf <<-EOF
	#!/usr/bin/env bash
	yes | etc-update --automode -3
EOF
chmod 755 /usr/local/bin/force-update-conf

force-update-conf
