#!/usr/bin/env bash
set -euo pipefail

cat > /etc/portage/package.accept_keywords/docker-gentoo-dev <<EOF
app-admin/ansible
app-admin/ansible-core
app-admin/ansible-lint
dev-java/mill-bin
dev-python/ansible-compat
EOF

mapfile PACKAGES < packages

NPROC=$(nproc)
export MAKEOPTS="--jobs ${NPROC} --load-average ${NPROC}"

emerge ${PACKAGES[@]}

# Clean distdir and pkgdir, since its contents will not be needed
# anymore.
drop-distdir
drop-pkgdir
