#!/usr/bin/env bash
set -euo pipefail

cat > /etc/portage/package.accept_keywords/docker-gentoo-dev <<EOF
app-admin/ansible
app-admin/ansible-core
app-admin/ansible-lint
dev-java/mill-bin
dev-lang/opencilk-bin
dev-python/ansible-compat

# LLVM, clang, iwyu
sys-devel/clang:18
<sys-devel/clang-common-19
sys-devel/clang-runtime:18
sys-devel/clang-toolchain-symlinks:18
sys-devel/llvm:18
sys-devel/llvm-toolchain-symlinks:18
<sys-devel/llvmgold-19
sys-libs/compiler-rt:18
sys-libs/compiler-rt-sanitizers:18
<sys-libs/libcxx-19
<sys-libs/libcxxabi-19
<sys-libs/libomp-19

~dev-util/include-what-you-use-0.22

dev-tex/rubber

# TeX Live
>=app-text/dvipsk-2024
app-text/dvisvgm
>=app-text/ps2pkm-1.8_p20240311
>=app-text/texlive-2024
>=app-text/texlive-core-2024
>=dev-libs/kpathsea-6.4.0
>=dev-libs/ptexenc-1.4.6
dev-python/latexrestricted
>=dev-tex/biber-2.20
>=dev-tex/biblatex-3.20
>=dev-tex/bibtexu-3.72_p20240311
>=dev-tex/glossaries-4.55
dev-tex/latex2pydata
>=dev-tex/latexmk-4.85
>=dev-tex/minted-3.4.0
>=dev-tex/tex4ht-20240311
>=dev-texlive/texlive-basic-2024
>=dev-texlive/texlive-bibtexextra-2024
>=dev-texlive/texlive-binextra-2024
>=dev-texlive/texlive-context-2024
>=dev-texlive/texlive-fontsextra-2024
>=dev-texlive/texlive-fontsrecommended-2024
>=dev-texlive/texlive-fontutils-2024
>=dev-texlive/texlive-formatsextra-2024
>=dev-texlive/texlive-games-2024
>=dev-texlive/texlive-humanities-2024
>=dev-texlive/texlive-langarabic-2024
>=dev-texlive/texlive-langchinese-2024
>=dev-texlive/texlive-langcjk-2024
>=dev-texlive/texlive-langcyrillic-2024
>=dev-texlive/texlive-langczechslovak-2024
>=dev-texlive/texlive-langenglish-2024
>=dev-texlive/texlive-langeuropean-2024
>=dev-texlive/texlive-langfrench-2024
>=dev-texlive/texlive-langgerman-2024
>=dev-texlive/texlive-langgreek-2024
>=dev-texlive/texlive-langitalian-2024
>=dev-texlive/texlive-langjapanese-2024
>=dev-texlive/texlive-langkorean-2024
>=dev-texlive/texlive-langother-2024
>=dev-texlive/texlive-langpolish-2024
>=dev-texlive/texlive-langportuguese-2024
>=dev-texlive/texlive-langspanish-2024
>=dev-texlive/texlive-latex-2024
>=dev-texlive/texlive-latexextra-2024
>=dev-texlive/texlive-latexrecommended-2024
>=dev-texlive/texlive-luatex-2024
>=dev-texlive/texlive-mathscience-2024
>=dev-texlive/texlive-metapost-2024
>=dev-texlive/texlive-music-2024
>=dev-texlive/texlive-pictures-2024
>=dev-texlive/texlive-plaingeneric-2024
>=dev-texlive/texlive-pstricks-2024
>=dev-texlive/texlive-publishers-2024
>=dev-texlive/texlive-xetex-2024
EOF

cat > /etc/portage/package.unmask/texlive <<EOF
>=app-text/dvipsk-2024
>=app-text/ps2pkm-1.8_p20240311
>=app-text/texlive-2024
>=app-text/texlive-core-2024
>=dev-libs/kpathsea-6.4.0
>=dev-libs/ptexenc-1.4.6
dev-python/latexrestricted
>=dev-tex/biber-2.20
>=dev-tex/biblatex-3.20
>=dev-tex/bibtexu-3.72_p20240311
>=dev-tex/glossaries-4.55
dev-tex/latex2pydata
>=dev-tex/latexmk-4.85
>=dev-tex/minted-3.4.0
>=dev-tex/tex4ht-20240311
>=dev-texlive/texlive-basic-2024
>=dev-texlive/texlive-bibtexextra-2024
>=dev-texlive/texlive-binextra-2024
>=dev-texlive/texlive-context-2024
>=dev-texlive/texlive-fontsextra-2024
>=dev-texlive/texlive-fontsrecommended-2024
>=dev-texlive/texlive-fontutils-2024
>=dev-texlive/texlive-formatsextra-2024
>=dev-texlive/texlive-games-2024
>=dev-texlive/texlive-humanities-2024
>=dev-texlive/texlive-langarabic-2024
>=dev-texlive/texlive-langchinese-2024
>=dev-texlive/texlive-langcjk-2024
>=dev-texlive/texlive-langcyrillic-2024
>=dev-texlive/texlive-langczechslovak-2024
>=dev-texlive/texlive-langenglish-2024
>=dev-texlive/texlive-langeuropean-2024
>=dev-texlive/texlive-langfrench-2024
>=dev-texlive/texlive-langgerman-2024
>=dev-texlive/texlive-langgreek-2024
>=dev-texlive/texlive-langitalian-2024
>=dev-texlive/texlive-langjapanese-2024
>=dev-texlive/texlive-langkorean-2024
>=dev-texlive/texlive-langother-2024
>=dev-texlive/texlive-langpolish-2024
>=dev-texlive/texlive-langportuguese-2024
>=dev-texlive/texlive-langspanish-2024
>=dev-texlive/texlive-latex-2024
>=dev-texlive/texlive-latexextra-2024
>=dev-texlive/texlive-latexrecommended-2024
>=dev-texlive/texlive-luatex-2024
>=dev-texlive/texlive-mathscience-2024
>=dev-texlive/texlive-metapost-2024
>=dev-texlive/texlive-music-2024
>=dev-texlive/texlive-pictures-2024
>=dev-texlive/texlive-plaingeneric-2024
>=dev-texlive/texlive-pstricks-2024
>=dev-texlive/texlive-publishers-2024
>=dev-texlive/texlive-xetex-2024
EOF
cp /etc/portage/package.{unmask,accept_keywords}/texlive

cat > /etc/portage/package.use/texlive <<EOF
app-text/texlive extra
app-text/texlive graphics
app-text/texlive luatex
app-text/texlive publishers
app-text/texlive science
app-text/texlive tex4ht

sys-devel/clang-runtime libcxx
EOF

cat >> /etc/portage/make.conf <<EOF
USE="\${USE} icu"
EOF

mapfile PACKAGES < packages

NPROC=$(nproc)
export MAKEOPTS="--jobs ${NPROC} --load-average ${NPROC}"

emerge -tv ${PACKAGES[@]}

# Clean distdir and pkgdir, since its contents will not be needed
# anymore.
drop-distdir
drop-pkgdir
