#!/usr/bin/env bash
set -eo pipefail

cat >> /etc/portage/package.use/docker-gentoo-dev <<EOF
llvm-core/clang-runtime libcxx
EOF
ABI_X86="64" emerge -1 clang-runtime

# Clean distdir and pkgdir, since its contents will not be needed
# anymore.
drop-distdir
drop-pkgdir
