#!/usr/bin/env bash

cat > /usr/local/bin/prepare-for-emerge <<-EOF
	#!/usr/bin/env bash
    set -euo pipefail

	NPROC=$(nproc)
	echo "MAKEOPTS=\"--jobs ${NPROC} --load-average ${NPROC}\"" >> /etc/portage/make.conf

    emerge --sync

    mirrorselect -s5
EOF
chmod 755 /usr/local/bin/prepare-for-emerge
