#!/usr/bin/env bash

set -euo pipefail

NO_DOCKER_CACHE="false"

while getopts :dn OPT; do
	case $OPT in
		d)
			set -x
			;;
		n)
			NO_DOCKER_CACHE="true"
			;;
		*)
			echo "usage: ${0##*/} [-d] [version]"
			exit 2
	esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

readonly CONTAINER_NAME="flowdalic/gentoo-dev"

if ! git diff-index --quiet HEAD --; then
    >&2 echo "ERROR: Uncommited changes, please commit"
    exit 1
fi

VERSION=$(date +%Y%m%d)
if [[ $(git tag -l "${VERSION}") ]]; then
    VERSION+=".$(date +%H%M)"
fi

readonly DOCKER_COORDINATES="${CONTAINER_NAME}:${VERSION}"

docker build \
	   --compress=true \
	   --tag="${DOCKER_COORDINATES}" \
	   --no-cache="${NO_DOCKER_CACHE}" \
	   .

docker push "${DOCKER_COORDINATES}"

git tag -m "${CONTAINER_NAME} ${VERSION}" "${VERSION}"

git push origin \
	master \
	"${VERSION}"
