#!/usr/bin/env bash

set -euo pipefail

NO_DOCKER_CACHE="false"

while getopts :dn OPT; do
	case $OPT in
		d)
			set -x
			;;
		n)
			NO_DOCKER_CACHE="true"
			;;
		*)
			echo "usage: ${0##*/} [-d] [version]"
			exit 2
	esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

readonly CONTAINER_NAME="flowdalic/gentoo-dev"

set +u
if [[ -z $1 ]]; then
	VERSION_GIVEN_VIA_ARGUMENT=false
else
	VERSION_GIVEN_VIA_ARGUMENT=true
fi
set -u

TAG_HEAD=true
if ! ${VERSION_GIVEN_VIA_ARGUMENT}; then
	set +e
	VERSION_TAG=$(git describe --match "[0-9]*.[0-9]*" HEAD 2>/dev/null)
	set -e
	if [[ -z $VERSION_TAG ]]; then
		echo "Current commit is not tagged, please tag it"
		exit 1
	fi
	VERSION=${VERSION_TAG}
else
	VERSION="${1}"
	# TODO: Abort if dirty.

	# TODO: See if the given tag exists and matches the current HEAD, if so, set TAG_HEAD=false
fi

readonly DOCKER_COORDINATES="${CONTAINER_NAME}:${VERSION}"

docker build \
	   --compress=true \
	   --tag="${DOCKER_COORDINATES}" \
	   --no-cache="${NO_DOCKER_CACHE}" \
	   .

docker push "${DOCKER_COORDINATES}"

if ${TAG_HEAD}; then
	git tag -s -m "${CONTAINER_NAME} ${VERSION}" "${VERSION}"
fi

git push origin \
	master \
	"${VERSION}"
